project:
  type: website
  output-dir: docs

filters:
- nceas-learning-hub/lh_theme
exercises: ### for custom theme callouts
  number: false ### see https://cambiotraining.github.io/quarto-course-template/materials/02-content_guidelines.html but does not work
editor: source
bibliography: book.bib

format:
  lh_theme-html

website:
  title: "coreR example (2024-01-01 - 2024-12-31)"
  reader-mode: false
  repo-url: https://github.com/nceas-learning-hub/coreR_testing

  favicon: _extensions/nceas-learning-hub/lh_theme/logo_lh_hex.png # learning hub logo on browser tab

  bread-crumbs: false
  navbar:
    right:
      - text: "Instructors"
        menu:
          - text: "Casey O'Hara"
            href: https://www.oharascience.com/
      - icon: github
        href: https://github.com/nceas-learning-hub/coreR_testing
        aria-label: GitHub

  sidebar:
    title: "Training Materials"
    style: "floating"
    search: true
    tools:
      - icon: house-door-fill
        href: https://www.nceas.ucsb.edu/learning-hub
      - icon: twitter
        href: https://twitter.com/ucsb_nceas
      - icon: github
        href: COURSE_URL
    contents:
      - index.qmd # preface
      - section: "Day 1"
        contents:
        - s01_r_rstudio_server_setup.qmd  ###  (coreRlessons v2024.11.07)
        - s02_git_setup.qmd  ###  (coreRlessons v2024.11.07)
        - s03_r_programming_introduction.qmd  ###  (coreRlessons v2024.11.07)
        - s04_r_quarto_literate_analysis.qmd  ###  (coreRlessons v2024.11.07)
        - s05_activity_reproducibility_lego.qmd  ###  (coreRlessons v2024.11.07)

  page-footer:
    center: "Copyright \u00a9 2024, NCEAS"
    ### NCEAS main website footer:
    # center: "\u00a9 The Regents of the University of California, All Rights Reserved"
    # could also include license info?


